version: '1.0'
services:
    hostname: openhim-mediator-xds
    container_name: xds-mediator
    volumes:
      # data is the directory which you want to persist the generated parquet files
      - ../data:/tmp
    environment:
     - 