version: '1.0'
services:
    image:
    network_mode: host
    container_name: xds-mediator
    volumes:
      - ../utils/dbz_event_to_fhir_config.json:/usr/src/Main/dbz_event_to_fhir_config.json
      # data is the directory which you want to persist the generated parquet files
      - ../data:/tmp
    environment:
     - FHIR_SERVER_URL=http://localhost:8099/openmrs/ws/fhir2/R4
     - RESOURCE_LIST=Patient,Encounter,Observation
     - FHIR_SERVER_USERNAME=admin
     - FHIR_SERVER_PASSWORD=Admin123

     